drop table if exists analysiscleaning.parameter_unit_to_loinc_unit_mapping;
create table analysiscleaning.parameter_unit_to_loinc_unit_mapping
(
	parameter_unit text,
	parameter_unit_clean text,
	loinc_unit text,
	evidence text
);

\copy analysiscleaning.parameter_unit_to_loinc_unit_mapping from ../development/loinc_unit_assignment/results/parameter_unit_to_loinc_mapping.csv with (delimiter ',', format csv);


drop table if exists analysiscleaning.parameter_unit_to_cleaned_unit;
create table analysiscleaning.parameter_unit_to_cleaned_unit
(
	parameter_unit text,
	parameter_unit_clean text,
	loinc_unit text,
	evidence text
);


\copy analysiscleaning.parameter_unit_to_loinc_unit_mapping from ../development/loinc_unit_assignment/results/parameter_unit_to_cleaned_unit.csv with (delimiter ',', format csv);

