--- Import diagnosis data from original
--- Parameters: schema

--- Supress notices
SET client_min_messages TO WARNING;


--------------------------------------------------------------------------------
-- Create table diagnosis_info
--------------------------------------------------------------------------------

drop table if exists :schema.diagnosis_info;

create table :schema.diagnosis_info as
select
	pat.pat_id,
	pat.epi_id,
	diag.diag_code,
	diag.diag_type,
	coalesce(map.intended_type, 'tüüp määramata') as diag_statistical_type
from
(
	select distinct
		epi_id,
		main_diag_code,
		'main_diagnosis' as diag_type,
		main_diag_statistical_type as statistical_type
	from original.main_diagnosis
	union
	select distinct
		epi_id,
		other_diag_code,
		'other_diagnosis' as diag_type,
		other_diag_statistical_type as statistical_type
	from original.other_diagnosis
	union
	select distinct
		epi_id,
		outer_cause_diag_code,
		'outer_cause' as diag_type,
		null as statistical_type
	from original.outer_cause_diagnosis
	union
	select distinct
		epi_id,
		by_illness_diag_code,
		'by_illness' as diag_type,
		null as statistical_type
	from original.by_illness_diagnosis
	union
	select distinct
		epi_id,
		compl_diag_code,
		'complication' as diag_type,
		null as statistical_type
	from original.complication_diagnosis
) as diag(epi_id, diag_code, diag_type, diag_statistical_type)
left join original.patient as pat
on diag.epi_id = pat.epi_id
left join mappings.diagnosis_statistical_type_map as map
on diag.diag_statistical_type = map.reported_type;
-- 82639
