-- NB! parameter_names must be without õ,ä,ö,ü


DO $$
begin
raise notice 'Parameter_name and parameter_unit to loinc mapping';
end;
$$;


-------------------------------------------------------------------------------------------------------
-- Import data from predefined csv
-------------------------------------------------------------------------------------------------------
set role :role;

drop table if exists :schema.latest_subspecial_cases;
create table :schema.latest_subspecial_cases
(
	dirty_code text,
	unit text,
	"loinc_code(T-luhend)" text,
	loinc_unit text
);

set search_path to :schema;
\copy latest_subspecial_cases from 'create_csvs_for_loinc_code_assignment/parameter_name_unit_mapping_to_loinc_code/predefined_mapping_csvs/latest_subspecial_cases.csv' with (delimiter ',', format csv, header);


-------------------------------------------------------------------------------------------------------
-- Create parameter_name and parameter_unit mapping to loinc code
-------------------------------------------------------------------------------------------------------


drop table if exists :schema.parameter_name_unit_to_loinc_mapping;
create table :schema.parameter_name_unit_to_loinc_mapping (
    parameter_name varchar,
    parameter_unit varchar,
    t_lyhend       varchar,
    loinc_code     varchar,
    substrate      varchar,
    evidence       varchar
);

insert into :schema.parameter_name_unit_to_loinc_mapping (parameter_name, parameter_unit, t_lyhend, evidence)
  select dirty_code, unit, "loinc_code(T-luhend)", 'latest_subspecial_cases' from :schema.latest_subspecial_cases;

reset role;

update :schema.parameter_name_unit_to_loinc_mapping as p
set loinc_code = e.loinc_no,
    substrate = e.system
from classifications.elabor_analysis as e
where e.t_lyhend = p.t_lyhend;

-------------------------------------------------------------------------------------------------------
-- Deleting wrong mapping
-------------------------------------------------------------------------------------------------------
-- Kui mapping on olemas nii PN -> loinc kui ka PN, PU -> loinc, siis ilmselgelt viimane on täpsem mapping ja kustutame
-- PN-> loinc ära
delete
from :schema.parameter_name_unit_to_loinc_mapping
where parameter_name in
      (
          select distinct p.parameter_name
          from :schema.parameter_name_to_loinc_mapping as p
                   inner join :schema.parameter_name_unit_to_loinc_mapping as pu
                              on p.parameter_name = pu.parameter_name
      );


-------------------------------------------------------------------------------------------------------
-- Unifying substrate
-------------------------------------------------------------------------------------------------------
-- Do not know, if some substrates belong to urine or blood
-- Therefore the CASE ... WHEN ... statement can be improved
update :schema.parameter_name_unit_to_loinc_mapping
set substrate = case
                    when substrate in
                         ('Ser', 'Bld/Tiss', 'Bld.dot', 'RBC', 'Plas', 'BldA', 'BldC', 'BldMV', 'BldV', 'BldCo',
                          'BldCoV', 'BldCoA', 'Bld^newborn', 'Ser+Bld', 'BldA+Inhl gas', 'Bld/Bone mar', 'BldA+BldMV',
                          'Bld.pos growth', 'BldA+Resp.alv')
                        then 'Bld'
                    when substrate in ('Stool', 'Urine sed') then 'Urine'
                    when substrate in
                         ('Periton fld+Ser/Plas', 'Ser/Plas+Plr fld', 'Ser/Plas.maternal^fetus', 'Ser/Plas+Synv fld',
                          'Ser+Plas') then 'Ser/Plas'
                    when substrate in ('XXX','') then NULL
                    else substrate
    end;

set search_path to :schema;
\copy (select distinct on (parameter_name, parameter_unit, t_lyhend, loinc_code, substrate) parameter_name, parameter_unit, t_lyhend, loinc_code, substrate, evidence from parameter_name_unit_to_loinc_mapping) to 'create_csvs_for_loinc_code_assignment/results/parameter_name_unit_to_loinc_mapping.csv' With (delimiter ',', format csv, header)


-- jooksutamine
--psql --host="$host" --dbname="$dbname" --file=parameter_name_unit_mapping_to_loinc_code/create_predefined_csv_parameter_name_unit_to_loinc_mapping.psql -v role="$role" -v schema=$schema 2>&1 | tee
