from .anonymised_tagger import AnonymisedTagger
from .event_segments_tagger import EventSegmentsTagger
from .event_header_tagger import EventHeaderTagger
from .event_token_tagger import EventTokenTagger
from .anonym_tagger import AnonymTagger
from .doctor_code_tagger import DoctorCodeTagger
from .doctor_tagger import DoctorTagger
from .header_word_tagger import HeaderWordTagger
from .specialty_tagger import SpecialtyTagger
from .event_date_tagger import EventDateTagger
from .event_token2_tagger import EventTokenConflictResolverTagger
