-- NB! parameter_names must be without õ,ä,ö,ü


DO $$
begin
raise notice 'Analysis_name and parameter_unit to loinc mapping';
end;
$$;


-------------------------------------------------------------------------------------------------------
-- Import data from predefined csv
-------------------------------------------------------------------------------------------------------
set role :role;

drop table if exists :schema.manual_cases;
create table :schema.manual_cases
(
	analysis_name text,
	parameter_unit text,
	elabor_t_lyhend text,
	t_yhik text
);

set search_path to :schema;
\copy manual_cases from 'create_csvs_for_loinc_code_assignment/analysis_name_parameter_unit_mapping_to_loinc_code/predefined_mapping_csvs/manual_cases.csv' with (delimiter ',', format csv, header);


-------------------------------------------------------------------------------------------------------
-- Create parameter_name and parameter_unit mapping to loinc code
-------------------------------------------------------------------------------------------------------


drop table if exists :schema.analysis_name_parameter_unit_to_loinc_mapping;
create table :schema.analysis_name_parameter_unit_to_loinc_mapping (
    analysis_name varchar,
    parameter_unit varchar,
    t_lyhend       varchar,
    loinc_code     varchar,
    substrate      varchar,
    evidence       varchar
);

insert into :schema.analysis_name_parameter_unit_to_loinc_mapping (analysis_name, parameter_unit, t_lyhend, evidence)
  select analysis_name, parameter_unit, elabor_t_lyhend, 'manual_cases' from :schema.manual_cases;

reset role;

update :schema.analysis_name_parameter_unit_to_loinc_mapping as p
set loinc_code = e.loinc_no,
    substrate = e.system
from classifications.elabor_analysis as e
where e.t_lyhend = p.t_lyhend;


-------------------------------------------------------------------------------------------------------
-- Unifying substrate
-------------------------------------------------------------------------------------------------------
-- Do not know, if some substrates belong to urine or blood
-- Therefore the CASE ... WHEN ... statement can be improved
update :schema.analysis_name_parameter_unit_to_loinc_mapping
set substrate = case
                    when substrate in
                         ('Ser', 'Bld/Tiss', 'Bld.dot', 'RBC', 'Plas', 'BldA', 'BldC', 'BldMV', 'BldV', 'BldCo',
                          'BldCoV', 'BldCoA', 'Bld^newborn', 'Ser+Bld', 'BldA+Inhl gas', 'Bld/Bone mar', 'BldA+BldMV',
                          'Bld.pos growth', 'BldA+Resp.alv')
                        then 'Bld'
                    when substrate in ('Stool', 'Urine sed') then 'Urine'
                    when substrate in
                         ('Periton fld+Ser/Plas', 'Ser/Plas+Plr fld', 'Ser/Plas.maternal^fetus', 'Ser/Plas+Synv fld',
                          'Ser+Plas') then 'Ser/Plas'
                    when substrate in ('XXX','') then NULL
                    else substrate
    end;

set search_path to :schema;
\copy (select distinct on (analysis_name, parameter_unit, t_lyhend, loinc_code, substrate) analysis_name, parameter_unit, t_lyhend, loinc_code, substrate, evidence from analysis_name_parameter_unit_to_loinc_mapping) to 'create_csvs_for_loinc_code_assignment/results/analysis_name_parameter_unit_to_loinc_mapping.csv' With (delimiter ',', format csv, header)


-- jooksutamine
--psql --host="$host" --dbname="$dbname" --file=parameter_name_unit_mapping_to_loinc_code/create_predefined_csv_parameter_name_unit_to_loinc_mapping.psql -v role="$role" -v schema=$schema 2>&1 | tee
