vocabulary = [
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Ee]mal?|EMAL?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "vanem",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Ii]sal?|ISAL?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "vanem",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Vv]anaemal?|VANAEMAL?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "vanavanem",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Vv]anaisal?|VANAISAL?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "vanavanem",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Tt]ütarlapse?l?|TÜTARLAPSE?L?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "laps",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Tt]ütar|[Tt]ütrel?|TÜTAR|TÜTREL?|[Tt]üdruku?l?|TÜDRUKU?L?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "laps",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Pp]oeg|[Pp]ojal?|POEG|POJAL?|[Pp]oiss?i?|POISS?I?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "laps",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Pp]oeglapse?l?|POEGLAPSE?L?|[Pp]oisslapse?l?|POISSLAPSE?L?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "laps",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Ll]oo[td]e|LOO[TD]E",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "loode",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Ll]apse?l?|LAPSE?L?|[Ll]astel?|LASTEL?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "laps",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Vv]anema?(te)?l?|VANEMA?(TE)?L?",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "vanem",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Pp]erekonnas?|PEREKONNAS?|[Ss]uguvõsas?|SUGUVÕSAS|[Pp]eres?|PERES",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "sugulane",
    },
    {
        "grammar_symbol": "SUBJECT",
        "regex_type": "SUBJECT",
        "_regex_pattern_": "[Ss]ilma|[Bb]ulbust?e",
        "_group_": 0,
        "_priority_": 0,
        "_validator_": lambda m: True,
        "value": "other",
    },
]
